version: '3'
services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src:/app/src
  mongo:
    image: mongo
    ports:
      - "27017:27017"
